### ISSUE TITLE
RPROMPT before left PROMPT?

### ISSUE THREAD

**Issue by fniessen** [robobenklein/p10k#4] opened 2019-06-26 10:59 UTC
Is there any possibility to get first the RPROMPT displayed, then a newline, and finally the left PROMPT?

**Comment by robobenklein** [comment] 2019-06-26 19:31
It's possible although async redraws might cause problems with the current codebase.

If the RPROMPT doesn't contain any async segments, then there shouldn't be any problem, but for async support to draw outside the current prompt line I'll need to do some thinking...

**Comment by robobenklein** [comment] 2019-06-26 21:23
Here's the simple solution if you don't mind that the RPROMPT is it's own line in the scrollback:

https://asciinema.org/a/VTqEf7FztS2u4i64Ec332Hc4C

Had to add a `NONRENDERABLE` display mode that allows direct output to avoid getting some extra spaces: https://github.com/robobenklein/zinc/commit/c9d75378db1266802a52715aaa6ced5f68b53141

One issue is that ZSH still thinks that the rprompt would be obstructed when the line gets too long, but otherwise it works as intended.

**Comment by robobenklein** [comment] 2019-06-26 21:24
If that's the solution you're looking for then I'll clean up the code, do docs, and put it into master.

**Comment by fniessen** [comment] 2019-06-27 07:59
Dear, it seems this is exactly what I want.  In fact, as the RPROMPT gives info over the last command (exit code, duration, time when it stopped), it makes more sense, for me, to get it placed before the prompt.

However, can't do it like in your video:

> prompt_zinc_setup rprompt-previous-line 
returns:
ZINC: No such preset found in /cygdrive/d/Users/fni/.dotfiles/plugins/oh-my-zsh/custom/themes/zinc/presets/.

What am I doing wrong?

PS- I'm having a Zinc up-to-date (last commit 4281aa1, on 2019-04-02).

**Comment by robobenklein** [comment] 2019-06-27 18:38
Sorry, I had only committed the preset to the dev branch so far, since it still had some bugs on some systems.

If you want, the preset is on the dev branch at https://github.com/robobenklein/zinc/blob/dev/presets/rprompt-previous-line.zincp.zsh

I haven't put it on master yet since on a RHEL system I have it seems to write-over the previous line for some reason...

**Comment by robobenklein** [comment] 2019-06-27 20:10
`prompt_zinc_setup rprompt-previous-line` should now work with master.

**Comment by fniessen** [comment] 2019-06-27 21:07
Hello, it almost work. Yes, it's now on 2 lines; but there is one white triangle almost at the end of the second line.

Can show you a pic if needed.

PS - You're incredible, reacting so quickly to my messages!  (Thanks a lot…)

**Comment by robobenklein** [comment] 2019-06-27 21:28
![image](https://user-images.githubusercontent.com/5423266/60302035-d2f78f80-9900-11e9-8c71-77d3f4a8c582.png)

Weird, I thought I fixed that... it still happens on the latest master?

**Comment by fniessen** [comment] 2019-06-28 07:26
![image](https://user-images.githubusercontent.com/1748469/60325108-c584e880-9986-11e9-8457-0a1108f6ade7.png)

seems alright now.  Thanks!!!

PS- I do think the timestamp should be 0-padded, always (at least, by default).

**Comment by robobenklein** [comment] 2019-06-28 07:46
About the timestamp, it's really just ZSH's prompt expansion where you can input your own strftime format for whatever you want: http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html

To generate the strftime format: http://strftime.net/

(I think you'd want `function zincs_time(){ REPLY="%D{%H:%M}" }`)

**Closed as completed** 2019-07-01 09:03 UTC
Labels: feature, research-required
